In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
import keras

Using TensorFlow backend.


In [3]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from keras.utils import np_utils

In [4]:
#load in the data set: 
jazz = pd.read_csv("data/jazz_csv.csv")
classical = pd.read_csv("data/classical_csv.csv")
country = pd.read_csv("data/country_csv.csv")
edm = pd.read_csv("data/edm_csv.csv")
rap = pd.read_csv("data/rap_csv.csv")
rock = pd.read_csv("data/rock_csv.csv")

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib

In [8]:
count = 0
features = []
genres = []
dataframes = {1:jazz, 2: classical, 3:country, 4:edm, 5: rap, 6: rock} #map genre dfs to index
for genre, dataframe in dataframes.items():
    count = 0
    for ind, row in dataframe.iterrows():
        count+=1
        features.append([row["acousticness"], row["danceability"], row["energy"],row["loudness"],row["speechiness"], row["tempo"], row["valence"]])
        genres.append(genre)

In [9]:
y = genres
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
dummy_y = np_utils.to_categorical(encoded_Y) #hot encoder matrix for classifying genre 
y = dummy_y
genres = y

In [10]:
unique_data = [list(x) for x in set(tuple(x) for x in genres)]

In [63]:
unique_data

[[0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]

In [12]:
np.unique(genres)

array([ 0.,  1.], dtype=float32)

In [14]:
genres_dict = {repr([ 1.,  0.,  0.,  0.,  0.,  0.]): "jazz",
               repr([ 0.,  1.,  0.,  0.,  0.,  0.]) : "classical", 
              repr([ 0.,  0.,  1.,  0.,  0.,  0.]): "country" , 
              repr([ 0.,  0.,  0.,  1.,  0.,  0.]): "edm" , 
              repr([ 1.,  0.,  0.,  0.,  1.,  0.]): "rap" ,
               repr([ 0.,  0.,  0.,  0.,  0.,  1.]): "rock"}

In [70]:
genres_dict = {"jazz": [ 1.,  0.,  0.,  0.,  0.,  0.], 
               "classical": [ 0.,  1.,  0.,  0.,  0.,  0.], 
               "country" : [ 0.,  0.,  1.,  0.,  0.,  0.], 
               "edm": [ 0.,  0.,  0.,  1.,  0.,  0.], 
               "rap": [ 1.,  0.,  0.,  0.,  1.,  0.], 
               "rock": [ 0.,  0.,  0.,  0.,  0.,  1.]
    }

In [16]:
genres_dict[repr([ 1.,  0.,  0.,  0.,  0.,  0.])]

'jazz'

In [18]:
X = features

In [19]:
len(features)

12548

In [149]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 21)

In [150]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [176]:
classifier = RandomForestClassifier(n_estimators = 30, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=30, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [179]:
y_pred = classifier.predict(X_test)

In [170]:
count2 = 0

In [171]:
y_train

array([[ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.]], dtype=float32)

In [172]:
for thing in X_test:
    if list(thing) == list([ 0.,  0.,  0.,  0.,  0.,  0.]):
        print(thing)
        count2+=1

In [167]:
count2

0

In [131]:
genres_dict

{'classical': [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 'country': [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 'edm': [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 'jazz': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 'rap': [1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 'rock': [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]}

In [65]:
for key, value in genres_dict.items():
    print(type(key))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [107]:
def get_genre(array):
    for key, value in genres_dict.items():
        #print(type(value))
        #print(type(array))
        if value == array:
            return key
    print("fucked up: ", array)
        

In [80]:
y_test[0]

array([ 0.,  0.,  0.,  1.,  0.,  0.], dtype=float32)

In [82]:
get_genre(list(y_test[0]))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


'edm'

In [96]:
len(y_test)


3137

In [99]:
list(y_test[3])

[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]

In [109]:
ctr = 0

In [111]:
for i in range(0,len(y_test)):
    if list(y_pred[i]) == None or list(y_test[i])== None:
        #print("hi")
        pass
    else:
        print("predicted: ", get_genre(list(y_pred[i])))#, "expected: ", get_genre(list(y_test[i])))
        #print(get_genre(list(y_test[i])))
        #print("hi")

fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  rock
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  classical
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  rock
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:

fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  classical
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
p

fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  rock
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked

fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
predicted:  rock
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  classical
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
p

predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  rock
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  classical
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0,

predicted:  classical
predicted:  rock
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  classical
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucke

fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.

predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predic

fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  classical
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  rock
predicted:  jazz
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:  rock
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
fucked up:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
predicted:  None
predicted:

In [101]:
if repr(y_test[0]) in genres_dict:
    print("yes")

In [180]:
accuracy = metrics.accuracy_score(y_pred, y_test)
accuracy

0.65731590691743702

In [173]:
y_pred = classifier.predict(X_test)

In [49]:
y_test

array([[ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.]], dtype=float32)

In [48]:
genres_dict[repr(y_test[0])]


KeyError: 'array([ 0.,  0.,  0.,  1.,  0.,  0.], dtype=float32)'

In [44]:
print(genres_dict.get(repr(y_test[0])))

None


In [33]:
y_test = np.vectorize(genres f_dict.get)(repr(y_test))

In [29]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
#Reverse factorize (converting y_pred from 0s,1s and 2s to Iris-setosa, Iris-versicolor and Iris-virginica
#reversefactor = dict(zip(range(6),definitions))
y_test = np.vectorize(genres_dict.get)(y_test)
y_pred = np.vectorize(genres_dict.get)(y_pred)
# Making the Confusion Matrix
print(pd.crosstab(y_test, y_pred, rownames=['Actual Species'], colnames=['Predicted Species']))

ValueError: If using all scalar values, you must pass an index

In [86]:
y_test

array([[None, None, None, None, None, None],
       [None, None, None, None, None, None],
       [None, None, None, None, None, None],
       ..., 
       [None, None, None, None, None, None],
       [None, None, None, None, None, None],
       [None, None, None, None, None, None]], dtype=object)

In [41]:
model = RandomForestClassifier()

In [61]:
model.fit(X[0:10000], genres[0:10000])

ValueError: setting an array element with a sequence.

In [26]:
from sklearn import metrics

In [44]:
predicted_labels = model.predict(features[10000:])

In [45]:
accuracy = metrics.accuracy_score(genres[10000:], predicted_labels)

In [47]:
genres[10000:]

array([[ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]], dtype=float32)

In [46]:
accuracy

0.16679748822605966